name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      info:
        description: 'Test'

  push:
    branches: [ master,develop ]

jobs:
  upload_mod:
    runs-on: windows-latest
    steps:
    - name: Get source
      uses: actions/checkout@v2

    - name: Get steamcmd
      run: |
        curl https://steamcdn-a.akamaihd.net/client/installer/steamcmd.zip --output steamcmd.zip
        Expand-Archive -Path steamcmd.zip
    
    - name: login steam
      run: |
        cd steamcmd
        dir
        steamcmd.exe +login anonymous +quit
      env:
        STEAM_LOGIN_NAME: ${{ secrets.STEAM_LOGIN_NAME }}
        STEAM_LOGIN_PASSWORD: ${{ secrets.STEAM_LOGIN_PASSWORD }}
      shell: cmd

    - name:
      run: |
        cd logs
        dir
        type stderr.txt

      if: ${{ always() }}
      shell: cmd