name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      info:
        description: 'Test'

jobs:
  say_hello:
    runs-on: windows-latest
    steps:
    - name: Get source
      uses: actions/checkout@v2

    - name: Get steamcmd
      run: |
        curl https://steamcdn-a.akamaihd.net/client/installer/steamcmd.zip --output steamcmd.zip
        Expand-Archive -Path steamcmd.zip
    
    - name: Check
      run: dir